### PR TITLE
fix!: algorithm for oneOfWeighted has better distribution

### LINKED ISSUE #46: oneOfWeighted incorrect distribution
Hey,
I'm opening a new issue, because this is an entirely different problem as #44 

Using `oneOfWeighted()` with more than 3 distributions makes it very difficult to get the expected probability distribution and the order with which we define the probabilities makes a difference.

```js
test(`averages to within ${DIFF_THRESHOLD * 100
  }% of the given probabilities`, t => {
    const n = 10000
    let i = -1

    const sums = {
      red: 0,
      green: 0,
      blue: 0,
      yellow: 0,
      fuchsia: 0
    }

    const fn = oneOfWeighted([
      [0.05, 'yellow'],
      [0.05, 'fuchsia'],
      [0.1, 'blue'],
      [0.2, 'green'],
      [0.6, 'red'],
    ])

    while (++i < n) sums[fn(i)]++

    console.log('oneOfWeighted.test.js:30 sums:', sums);

    t.assert(diffBetween(sums.red / n, 0.6) <= DIFF_THRESHOLD)
    t.assert(diffBetween(sums.green / n, 0.2) <= DIFF_THRESHOLD)
    t.assert(diffBetween(sums.blue / n, 0.1) <= DIFF_THRESHOLD)
    t.assert(diffBetween(sums.yellow / n, 0.05) <= DIFF_THRESHOLD)
    t.assert(diffBetween(sums.fuchsia / n, 0.05) <= DIFF_THRESHOLD)
  })

```

logs `{ red: 6284, green: 1693, blue: 1008, yellow: 536, fuchsia: 479 }`

whereas a distribution like this:
```js
const fn = oneOfWeighted([
      [0.05, 'yellow'],
      [0.05, 'fuchsia'],
      [0.2, 'green'],
      [0.1, 'blue'],
      [0.6, 'red'],
    ])
```

logs `{ red: 5936, green: 2029, blue: 1020, yellow: 536, fuchsia: 479 }`

And yet again:

```
const fn = oneOfWeighted([
      [0.6, 'red'],
      [0.2, 'green'],
      [0.1, 'blue'],
      [0.05, 'yellow'],
      [0.05, 'fuchsia'],
    ])
```

logs `{ red: 5923, green: 2087, blue: 0, yellow: 0, fuchsia: 1990 }`

Blue is 0 here, because `flip()` in `fictional/utils/flip.js` has only odd identities left. Also, the remaining probability when we try to pick `blue` or `yellow` in the last example is `0.5` which means the modulus of 2 can never be greater than 1.

I think the best approach is to avoid using flip() here put the selection logic directly into `oneOfWeighted`. I'm trying my luck on a prototype asap.

### PR DESCRIPTION
**Pull request by ctholho**
fixes #46

### CODE REVIEW

File: oneOfWeighted.js [hunk 1]
```diff
@@ -11,20 +11,14 @@ function oneOfWeighted(a, b) {
...
-
-  while (++i < n) {
-    sample = samples[i]
-    p = sample[0] / pRemaining
-    pRemaining -= p
-
-    if (flip(id, p)) {
-      return resolve(id, sample[1])
+  var id = hash(input, 'oneOfWeighted')
+  const prob = (id % 1_000_000) / 1_000_000
```
Comment (justinvdm) [inline oneOfWeighted.js:15]: `hash()` gives us back a 53-bit int, so I think we might be truncating the range with the `/ 1_000_000`, which could affect the quality of the results. Could we do `id / Number.MAX_SAFE_INTEGER` here instead?

File: oneOfWeighted.js [hunk 2]
```diff
@@ -11,20 +11,14 @@ function oneOfWeighted(a, b) {
...
+
+  let cumulative = 0;
+  for (const [probability, value] of samples) {
```
Comment (justinvdm) [inline oneOfWeighted.js:18]: When I created this project 5 years ago, I had the brainwave of writing it only in es5 to avoid a build step. I'm not sure if that decision was the right one, but unfortunately it means for now we need to write the code as es5 for linting to pass. I'm sorry about this, I realise it is absurd to ask someone to write es5 in 2025 :)

```suggestion
  var cumulative = 0;
  for (var i = 0; i < samples.length; i++) {
    var probability = samples[i][0];
    var value = samples[i][1];
```

File: oneOfWeighted.js (hunk 1 above)
Comment (justinvdm) [reply oneOfWeighted.js:15]: It turns out my suggestion fails the tests (the diff threshold is greater than 6.5%), whereas yours doesn't. I can't understand why. So lets go for your change - scratch my suggestion :) Can you help me understand why 1M works better?

```suggestion
  var prob = (id % 1000000) / 1000000
```

File: tests/oneOfWeighted.test.js [hunk 3]
```diff
@@ -29,6 +30,128 @@ test(`averages to within ${
   t.assert(diffBetween(sums.blue / n, 0.3) <= DIFF_THRESHOLD)
```
Comment (justinvdm) [inline tests/oneOfWeighted.test.js:30]:
```suggestion
  t.assert(diffBetween(sums.green / n, 0.2) <= DIFF_THRESHOLD)
  t.assert(diffBetween(sums.blue / n, 0.1) <= DIFF_THRESHOLD)
  // maybe yellow and fuchsia here too?
```

**Comment by justinvdm** [comment]
@ctholho I should really add contribution guidelines and CI for this project. For now, can you do these to run checks for your changes and update the docs and tests?
```
# checks
yarn lint
yarn test

# update snapshot tests
yarn test -u

# update docs (when code examples yield different results, e.g. for breaking changes)
yarn build:docs
```

File: oneOfWeighted.js (hunk 2 above)
Comment (ctholho) [reply oneOfWeighted.js:18]: alright. happy to comply.

File: oneOfWeighted.js (hunk 1 above)
Comment (ctholho) [reply oneOfWeighted.js:15]: I tried today again many different settings and don't understand it at all. I figured in the end it doesn't really matter because only the probabilities the user defined in the array are important. It's unlikely they would define values like `0.000004` and want to run the function more than a million times. Right now, somehow 1 million gave the best results with many different things I tried.

On the other hand: If we break backwards compatibility we should do it right the first time. So I'll take some more time to look into alternatives.

File: oneOfWeighted.js [hunk 4]
```diff
@@ -11,20 +11,14 @@ function oneOfWeighted(a, b) {
...
-  var p
-
-  while (++i < n) {
-    sample = samples[i]
-    p = sample[0] / pRemaining
-    pRemaining -= p
-
-    if (flip(id, p)) {
-      return resolve(id, sample[1])
+  var id = hash(input, 'oneOfWeighted')
```
[the remark this answers is not in the document]
Comment (ctholho) [reply oneOfWeighted.js:14]: good spot. I think I changed it for debugging.

File: oneOfWeighted.js (hunk 1 above)
Comment (justinvdm) [reply oneOfWeighted.js]: Thanks @ctholho. I think it might actually matter though - for some reason using 1M  to convert the id number hash to a decimal to results in `oneOfWeighted()` working much more accurately compared to using 2^52 instead. Accurately as in, the probability of a value getting chosen is much closer to the probability defined by the user (based on these tests, it stays within 6.5% of the probability value the user defined).

So even if there's still something for us to figure out, from an empirical point of view, the 1M value you have here is a better choice, so I'll merge it like this!

**Comment by justinvdm** [comment]
@ctholho thank you! I've updated fictional and copycat accordingly, you can use it in fictional 3.0.1 and copycat 6.0.0

**Comment by ctholho** [comment]
thanks a bunch! 🎉
