### PR TITLE
fix: oneOfWeighted remaining probability

### LINKED ISSUE #44: oneOfWeighted can not resolve
I'm trying to play around with `oneOfWeighted()` and I see that it quite often has problems finding a solution.

Play around with it yourself: https://stackblitz.com/edit/stackblitz-starters-fp4nfavx?file=index.js
```
import { oneOfWeighted } from 'fictional';

const dist = [
  [0.7, 'foo'],
  [0.15, 'bar'],
  [0.1, 'baz'],
  [0.05, 'lol'],
];

for (let i = 0; i < 1000; i++) {
  const key = `some-key-${i}`;
  console.log('result', key);
  const test = oneOfWeighted(key, dist);
}
```

E.g. this will fail at `some-key-2` with: `Error: Unexpectedly reached end of oneOfWeighted() unresolved. If you see this please file a bug.`

Playing around and trying different values for `const key` results in the same error after 10 or 25 tries.

Taking a look at the source code, could it be that we have some floating point inaccuracies here: https://github.com/oftherivier/fictional/blob/master/oneOfWeighted.js#L23-L23

### PR DESCRIPTION
**Pull request by ctholho**
fixes #44

### CODE REVIEW

File: oneOfWeighted.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ function oneOfWeightedMain(input, samples) {
   while (++i < n) {
     sample = samples[i]
     p = sample[0] / pRemaining
-    pRemaining -= p
+    pRemaining -= sample[0]
```
Comment (justinvdm) [inline oneOfWeighted.js:24]: Ah!

File: tests/oneOfWeighted.test.js [hunk 2]
```diff
@@ -4,30 +4,35 @@ const { diffBetween } = require('./utils')
...
 
-  const fn = oneOfWeighted([
-    [0.6, 'red'],
-    [0.1, 'green'],
-    [0.3, 'blue']
-  ])
+    const fn = oneOfWeighted([
+      [0.6, 'red'],
+      [0.2, 'green'],
+      [0.1, 'blue']
```
Comment (justinvdm) [inline tests/oneOfWeighted.test.js:23]: @ctholho only after landing and attempting to release did I realise we need `,`'s here (sorry, embarassingly fictional does not yet have CI).

After fixing the syntax though, it seems as though the test fail. Your fix and the test's logic both seem correct though, so my gut feeling is there is something else (that was already) broken in `oneOfWeighted`'s implementation.

I unfortunately don't enough time right now to investigate further though, so for now I'll re-open the issue and revert this PR's changes. Feel free to pick it up from there, otherwise I'll look into it further when I some time.

Hope that makes sense!

**Comment by ctholho** [comment]
Oh, damn. sorry, totally my fault. I fixed the test, saw that it failed but got a call and forgot to mark this PR as draft. 🤡
Sorry for the revert and hassle!

I'll look into it.
